#[repr(C)]
pub enum Tags {
    TagEnd = 0,
    SesFingerprint,
    SesListenport,
    SesListenportEnd,
    SesVersionMajor,
    SesVersionMinor,
    SesVersionTiny,
    SesVersionTag,
    SesFlags,
    SesAlertMask,
    SesListenInterface,
    TorFilename = 0x100,
    TorTorrent,
    TorTorrentSize,
    TorInfohash,
    TorInfohashHex,
    TorMagnetlink,
    TorTrackerUrl,
    TorResumeData,
    TorResumeDataSize,
    TorSavePath,
    TorName,
    TorPaused,
    TorAutoManaged,
    TorDuplicateIsError,
    TorUserData,
    TorSeedMode,
    TorOverrideResumeData,
    TorStorageMode,
    SetUploadRateLimit = 0x200,
    SetDownloadRateLimit,
    SetLocalUploadRateLimit,
    SetLocalDownloadRateLimit,
    SetMaxUploadSlots,
    SetMaxConnections,
    SetSequentialDownload,
    SetSuperSeeding,
    SetHalfOpenLimit,
    SetPeerProxy,
    SetWebSeedProxy,
    SetTrackerProxy,
    SetDhtProxy,
    SetProxy,
    SetAlertMask,
}
